module.exports = {
	config: {
		name: "hentai",
		aliases: ["milf"],
		version: "1.0",
		author: "ʬɸ satoru gojo ɸʬ", // do not change this credits
		countDown: 5,
		role: 0,
		shortDescription: "send you pic of girls anime Hentai",
		longDescription: "sends u pic of girls animr Hentai",
		category: "18+",
		guide: "{pn}"
	},

	onStart: async function ({ message }) {
	 var link = [ 
"https://i.ibb.co/YPwkx26/image.jpg",
"https://i.ibb.co/0X7TWZg/image.jpg",
"https://i.ibb.co/TknL43Y/image.jpg",
"https://i.ibb.co/Gs913Bc/image.jpg",
"https://i.ibb.co/Y3NFZ9n/image.jpg",
"https://i.ibb.co/jzzRpDn/image.jpg",
"https://i.ibb.co/jzzRpDn/image.jpg",
"https://i.ibb.co/WGXF0zj/image.jpg",
"https://i.ibb.co/K2yJwzC/image.jpg",
"https://i.ibb.co/SdXPrg1/image.jpg",
"",
"https://i.ibb.co/FnMkK5n/image.jpg",
"https://i.ibb.co/wrxykRG/image.jpg",
"https://i.ibb.co/D16T8fB/image.jpg",
"https://i.ibb.co/3zMpZTV/image.jpg",
"https://i.ibb.co/zh55rC3/image.jpg",
"https://i.ibb.co/JKthyfY/image.jpg",
"https://i.ibb.co/T1RKRLQ/image.jpg",
"https://i.ibb.co/nRJPCSb/image.jpg",
"https://i.ibb.co/wKXWmfg/image.jpg",
"https://i.ibb.co/MSD3KJR/image.jpg",
"https://i.ibb.co/HxLsS55/image.jpg",
"https://i.ibb.co/SQ1M0Jr/image.jpg",
"https://i.ibb.co/M2nRQ6n/image.jpg",
"https://i.ibb.co/chJ1XXc/image.jpg",
"https://i.ibb.co/V23DW99/image.jpg",
"https://i.ibb.co/mT8TYhB/image.jpg",
"https://i.ibb.co/gJkW33P/image.jpg",
"https://i.ibb.co/GQjkmk4/image.jpg",
"https://i.ibb.co/rfShfTQ/image.jpg",
"https://i.ibb.co/2K9pgzD/image.jpg",
"https://i.ibb.co/SRZ20Cj/image.jpg",
"https://i.ibb.co/znr3qKb/image.jpg",
"https://i.ibb.co/ckbXcDY/image.jpg",
"https://i.ibb.co/rHqBCD6/image.jpg",
"https://i.ibb.co/znr3qKb/image.jpg",
"https://i.ibb.co/ckbXcDY/image.jpg",
"https://i.ibb.co/HBLswDb/image.jpg",
"https://i.ibb.co/pJycWGm/image.jpg",
"https://i.ibb.co/nB2VxTD/image.jpg",
"https://i.ibb.co/YDZXDv4/image.jpg",
"https://i.ibb.co/Qcv77kX/image.jpg",
"https://i.ibb.co/wKXWmfg/image.jpg",
"https://i.ibb.co/nRJPCSb/image.jpg",
"https://i.ibb.co/T1RKRLQ/image.jpg",
"https://i.ibb.co/JKthyfY/image.jpg",
"https://i.ibb.co/z2hMQnV/image.jpg",
"https://i.ibb.co/rHqBCD6/image.jpg",
"https://i.ibb.co/dGwk7Nm/image.jpg",
"https://i.ibb.co/VWyxb0G/image.jpg",
"https://i.ibb.co/BnwZJ9T/image.jpg",
"https://i.ibb.co/0KLDCr5/image.jpg",
"https://i.ibb.co/5s6WyBH/image.jpghttps://i.ibb.co/5s6WyBH/image.jpg",
"https://i.ibb.co/B3kQXTz/image.jpg",
"https://i.ibb.co/qrTmxws/image.jpg",
"https://i.ibb.co/YyHsHKh/image.jpg",
"https://i.ibb.co/zGvwy7B/image.jpg",
"https://i.ibb.co/N3xcgC6/image.jpg",
"https://i.ibb.co/QdjGWh3/image.jpg",
"https://i.ibb.co/kMQQhtJ/image.jpg",
"https://i.ibb.co/fkRv6T3/image.jpg",
"https://i.ibb.co/k26H4cp/image.jpg",
"https://i.ibb.co/JvtHTQt/image.jpg",
"https://i.ibb.co/DD0jmKr/image.jpg",
"https://i.ibb.co/QpTKn3Z/image.jpg",
"https://i.ibb.co/VWyxb0G/image.jpg",
"https://i.ibb.co/QFFkYPR/image.jpg",
"https://i.ibb.co/0Kg22Wn/image.jpg",
"https://i.ibb.co/849fCW1/image.jpg",
"https://i.ibb.co/mDVmJPS/image.jpg",
"https://i.ibb.co/pQg9m9F/image.jpg",
"https://i.ibb.co/gPFN0pp/image.jpg",
"https://i.ibb.co/Fbf5Lky/image.jpg",
"https://i.ibb.co/gPFN0pp/image.jpg",
"https://i.ibb.co/YLVc78b/image.jpg",
"https://i.ibb.co/J76bQT4/image.jpg",
"https://i.ibb.co/YLVc78b/image.jpg",
"https://i.ibb.co/5WMg4BZ/image.jpg",
"https://i.ibb.co/YLVc78b/image.jpg",
"https://i.ibb.co/5rw2r2z/image.jpg",
"https://i.ibb.co/5WMg4BZ/image.jpg",
"https://i.ibb.co/YLVc78b/image.jpg",
"https://i.ibb.co/J76bQT4/image.jpg",
"https://i.ibb.co/YLVc78b/image.jpg",
"https://i.ibb.co/5rw2r2z/image.jpg",
"https://i.ibb.co/55nfZmd/image.jpg",
"https://i.ibb.co/zNrrqrS/image.jpg",
"https://i.ibb.co/4j8Mpqd/image.jpg",
"https://i.ibb.co/M6TnZ1L/image.jpg",
"https://i.ibb.co/N3xcgC6/image.jpg",
"https://i.ibb.co/1052cHq/image.jpg",
  ]
let img = link[Math.floor(Math.random()*link.length)]
message.send({
  body: '[________________________\n🥵𝙃𝙚𝙣𝙩𝙖𝙞 𝙖𝙣𝙞𝙢𝙚 𝙢𝙞𝙡𝙛\n_____________________________]',attachment: await global.utils.getStreamFromURL(img)
})
}
     }
